@ImageAIProxy_HostAddress = http://localhost:5231

### Probar el endpoint /process-image
POST {{ImageAIProxy_HostAddress}}/process-image
Content-Type: application/json
Accept: application/json

{
  "Base64Image": "iVBORw0KGgoAAAANSUhEUgAAAAUA...JRU5ErkJggg=="
}
